spring.data.mongodb.uri=${MONGO_URL:mongodb://localhost:27017/dev}

spring.freemarker.suffix=.ftl
minio.url=${MINIO_URL:http://localhost:9000}
minio.access-key=${MINIO_ACCESS_KEY:minioadmin}
minio.secret-key=${MINIO_SECRET_KEY:minioadmin123}
minio.bucket=${MINIO_BUCKET:knote}
